In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
df= pd.read_csv('/sms.csv', sep='\t', names=['Status', 'Message'])

In [5]:
df.head()

Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
print(len(df))
print(len(df[df.Status=='spam']))
print(len(df[df.Status=='ham']))


5572
747
4825


In [12]:
df.loc[df['Status']=='ham', 'Status']= 1

In [11]:
df.loc[df['Status']=='spam', 'Status']= 0

In [13]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [14]:
df_x= df['Message']
df_y= df['Status']

In [49]:
cv= TfidfVectorizer(min_df= 1, stop_words='english') #min_df: how many the word if it is repeated would be gotten

In [17]:
doc1= 'the quick brown fox'
doc2= 'the lazy dog'
doc3= 'the quick brown cat'

In [19]:
cv= TfidfVectorizer()
X= cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())#['brown' 'cat' 'dog' 'fox' 'lazy' 'quick' 'the']
print(X.toarray())

['brown' 'cat' 'dog' 'fox' 'lazy' 'quick' 'the']
[[0.4804584  0.         0.         0.63174505 0.         0.4804584
  0.37311881]
 [0.         0.         0.65249088 0.         0.65249088 0.
  0.38537163]
 [0.4804584  0.63174505 0.         0.         0.         0.4804584
  0.37311881]]


In [20]:
cv= TfidfVectorizer(min_df=2)
X= cv.fit_transform([doc1, doc2, doc3])
print(cv.get_feature_names_out())
print(X.toarray())

['brown' 'quick' 'the']
[[0.61980538 0.61980538 0.48133417]
 [0.         0.         1.        ]
 [0.61980538 0.61980538 0.48133417]]


In [21]:
x_train, x_test, y_train, y_test= train_test_split(df_x, df_y, test_size= 0.2, random_state= 4)

In [23]:
print(len(x_test))
print(len(y_train))

1115
4457


In [24]:
x_train, x_test, y_train, y_test

(1457    U sleeping now.. Or you going to take? Haha.. ...
 472     How long has it been since you screamed, princ...
 2481    Urgent! call 09066612661 from landline. Your c...
 243     Okay. No no, just shining on. That was meant t...
 1413    Wen ur lovable bcums angry wid u, dnt take it ...
                               ...                        
 3671                        Ok thanx... Take care then...
 709     To review and KEEP the fantastic Nokia N-Gage ...
 2487           I dont thnk its a wrong calling between us
 174     Bloody hell, cant believe you forgot my surnam...
 1146    Thank you, winner notified by sms. Good Luck! ...
 Name: Message, Length: 4457, dtype: object,
 4004    somewhere out there beneath the pale moon ligh...
 2276           Is that on the telly? No its Brdget Jones!
 4498                                                   Ok
 3755    Bloomberg -Message center +447797706009 Why wa...
 111              What is the plural of the noun research?
           

In [26]:
cv= TfidfVectorizer(min_df=1, stop_words= 'english')
x_traincv= cv.fit_transform(['hi how are you doing', "hi what's up", "wow that's great"])
feature_names= cv.get_feature_names_out()

# Print the feature names and the TF-IDF matrix


In [27]:
print(feature_names)
print(x_traincv.toarray())


['doing' 'great' 'hi' 'wow']
[[0.79596054 0.         0.60534851 0.        ]
 [0.         0.         1.         0.        ]
 [0.         0.70710678 0.         0.70710678]]


In [29]:
cv1= TfidfVectorizer(min_df= 1, stop_words='english')

In [30]:
x_traincv= cv1.fit_transform(x_train)
a= x_traincv.toarray()
a[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [31]:
x_testcv= cv1.transform(x_test)
x_testcv.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
mnb= MultinomialNB()

In [38]:
y_train= y_train.astype('int')
print(y_train)

1457    1
472     1
2481    0
243     1
1413    1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4457, dtype: int64


In [ ]:
mnb.fit(x_traincv, y_train)

In [ ]:
MultinomialNB()

In [41]:
testmessage= x_test.iloc[0]
testmessage

'somewhere out there beneath the pale moon light someone think in of u some where out there where dreams come true... goodnite &amp; sweet dreams'

In [43]:
predictions= mnb.predict(x_testcv)
predictions

array([1, 1, 1, ..., 1, 1, 0])

In [44]:
a= np.array(y_test)
a

array([1, 1, 1, ..., 1, 1, 0], dtype=object)

In [45]:
count_matches=0
for i in range(len(predictions)):
  if predictions[i]==a[i]:
    count_matches= count_matches+1

In [46]:
count_matches

1068

In [47]:

len(predictions)

1115

In [48]:

1068/1115.0

0.957847533632287