### Word Embedding Techniques using Embedding Layer in Keras

In [65]:
### Libraries Used tensorflow > 2.0 and keras

In [66]:
## tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot


In [67]:
##sentences
sentences= ["the glass of milk", "the glass of juice", "the cup of tea", "I am a good boy", "I am a good developer", "Understand the meaning of words", "your videos are good"]

In [68]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [69]:
### Vocabs size
voc_size= 10000

### One Hot Representation

In [70]:
onehot_rep= [one_hot(words, voc_size) for words in sentences]
print(onehot_rep)

[[8531, 9479, 7990, 6391], [8531, 9479, 7990, 1714], [8531, 8238, 7990, 9983], [808, 2316, 3465, 6984, 7391], [808, 2316, 3465, 6984, 2076], [1418, 8531, 3231, 7990, 5649], [154, 8307, 3632, 6984]]


### Word Embedding Representation

In [71]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [72]:
sentence_length= 8
embedded_docs= pad_sequences(onehot_rep, padding='post', maxlen=sentence_length)
print(embedded_docs)

[[8531 9479 7990 6391    0    0    0    0]
 [8531 9479 7990 1714    0    0    0    0]
 [8531 8238 7990 9983    0    0    0    0]
 [ 808 2316 3465 6984 7391    0    0    0]
 [ 808 2316 3465 6984 2076    0    0    0]
 [1418 8531 3231 7990 5649    0    0    0]
 [ 154 8307 3632 6984    0    0    0    0]]


In [73]:
embedding_dim=10

In [74]:
model= Sequential()
model.add(Embedding(voc_size, embedding_dim, input_length= sentence_length))
#model.compile('adam', 'mse')

In [75]:
## Expicitly building the model
model.build(input_shape=(None, sentence_length))

In [76]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step
[[[ 0.03001713 -0.01924721 -0.01719568 -0.02945783  0.03267456
    0.00845128 -0.03870701  0.03827338 -0.03485578  0.02084886]
  [-0.0263018   0.01599922  0.01678387  0.02591267  0.04214943
   -0.02913859 -0.02607424  0.01557303 -0.02318821  0.04205123]
  [-0.01773211  0.02537224  0.03094319  0.01019954  0.00765485
   -0.01743877 -0.02142055  0.03913976  0.04645011 -0.01419897]
  [ 0.00083728 -0.03392832  0.00655762  0.00588393  0.02405516
   -0.04034752 -0.00396546 -0.02850298 -0.03205919 -0.02237659]
  [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017
   -0.02832514 -0.02205814 -0.01096712 -0.04100211  0.01597482]
  [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017
   -0.02832514 -0.02205814 -0.01096712 -0.04100211  0.01597482]
  [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017
   -0.02832514 -0.02205814 -0.01096712 -0.04100211  0.01597482]
  [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017
   -0.028

In [78]:
embedded_docs[0]

array([8531, 9479, 7990, 6391,    0,    0,    0,    0], dtype=int32)

In [79]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[[ 0.03001713 -0.01924721 -0.01719568 -0.02945783  0.03267456  0.00845128
  -0.03870701  0.03827338 -0.03485578  0.02084886]
 [-0.0263018   0.01599922  0.01678387  0.02591267  0.04214943 -0.02913859
  -0.02607424  0.01557303 -0.02318821  0.04205123]
 [-0.01773211  0.02537224  0.03094319  0.01019954  0.00765485 -0.01743877
  -0.02142055  0.03913976  0.04645011 -0.01419897]
 [ 0.00083728 -0.03392832  0.00655762  0.00588393  0.02405516 -0.04034752
  -0.00396546 -0.02850298 -0.03205919 -0.02237659]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814

In [80]:
print(model.predict(embedded_docs)[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[ 0.03001713 -0.01924721 -0.01719568 -0.02945783  0.03267456  0.00845128
  -0.03870701  0.03827338 -0.03485578  0.02084886]
 [-0.0263018   0.01599922  0.01678387  0.02591267  0.04214943 -0.02913859
  -0.02607424  0.01557303 -0.02318821  0.04205123]
 [-0.01773211  0.02537224  0.03094319  0.01019954  0.00765485 -0.01743877
  -0.02142055  0.03913976  0.04645011 -0.01419897]
 [ 0.01911746 -0.04229565  0.04496671 -0.02533388  0.03207758 -0.01420309
   0.02341297 -0.0087324  -0.03873476  0.04510434]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814 -0.01096712 -0.04100211  0.01597482]
 [ 0.02726002  0.02610994  0.03557538 -0.0018124  -0.03068017 -0.02832514
  -0.02205814